add_newline = false

[character]
success_symbol = "[»](fg:#fee074)[»](fg:#f34f4d)[»](fg:#7ad88e)"
vicmd_symbol = "[«](fg:#7ad88e)[«](fg:#f34f4d)[«](fg:#fee074)"
# success_symbol = "[](fg:#bb98eb)[](fg:#8accfe)[](fg:#7ad88e)"
error_symbol = "[✗](bold red)"

[git_metrics]
disabled = false

[directory.substitutions]
"~/Escritorio" = "\uF6C3 "
"~/Descargas" = "\uf019 "
"~/Documentos" = "\uf719 "
"~/Imágenes" = "\ue244 "
"~/Música" = "\ufc58 "
"~/Vídeos" = "\uf191 "
"~/Git" = "\uf7a1 "
"/run/media/crag" = "\ufa52"

